### ISSUE TITLE
Terminal is significantly scaled down on MacOS

### ISSUE THREAD

**Issue by l4tte** [tommyettinger/BearLibTerminal#2]
The code
```C
#include <stdio.h>
#include "BearLibTerminal.h"

int main()
{
    terminal_open();

    terminal_print(1, 1, "Hello, world!");
    terminal_refresh();

    while (terminal_read() != TK_CLOSE);

    terminal_close();
}
```
As taken from [here](http://foo.wyrd.name/en:bearlibterminal) will compile and run just fine, but the text is significantly scaled to 25% of the display

![image](https://user-images.githubusercontent.com/34426037/94081915-bc730900-fdcd-11ea-8834-43eb861cae46.png)

This happens with all BearLibTerminal terminals, for example, the SampleOmni program looks like this
<img width="752" alt="Screen Shot 2020-09-23 at 6 52 00 PM" src="https://user-images.githubusercontent.com/34426037/94081967-df052200-fdcd-11ea-9f44-634b17047e3b.png">

And the mouse program looks like this (Mouse is in top right corner of screen)
<img width="752" alt="Screen Shot 2020-09-23 at 6 53 06 PM" src="https://user-images.githubusercontent.com/34426037/94082049-06f48580-fdce-11ea-8182-da2c8001a362.png">

**Comment by tommyettinger** [comment]
It might be better to submit this to https://github.com/cfyzium/bearlibterminal , since cfyzium is the original author. I can't actually compile BearLibTerminal on Windows because I don't know what arcane configuration is needed to let it build and link on any other system (I can make a .dll file, but it fails to load on anyone else's machine). I definitely can't test on Mac, because I don't have a MacOS system, none of my machines are probably powerful enough to run a Hackintosh or MacOS VM, and I am absolutely not buying one of their developer-hostile signing-required padded-cell-computers. I don't think I can even merge PRs because I can't verify if they build... Needless to say, I don't currently use BLT.

Closing because there's nothing I can do about this. This is a valid issue, just for a different repo.

**Comment by l4tte** [comment]
Oops, that's my bad! I'll submit it there, thanks!
