### ISSUE TITLE
edit to fix compiling with new mingw 

### ISSUE THREAD

**Issue by hero-clashes** [tommyettinger/BearLibTerminal#3]
you need to edit log.cpp
and add 
```
#define _POSIX_THREAD_SAFE_FUNCTIONS <--
#include "Log.hpp"
```
to make it compile
I am using mingw from MSYS2

**Comment by hero-clashes** [comment]
I figured out this isn't the right repo

**Comment by tommyettinger** [comment]
To be honest, I never got this version to compile a .NET-compatible DLL, at least one that worked on more machines than my own. BLT was hosted on BitBucket a while ago, but BitBucket got rid of Mercurial support (their one saving grace), and so I don't know if BLT stayed there. I do hope my one fix, regarding box drawing characters, can get into the BLT main repo, if it's still being updated.

**Comment by hero-clashes** [comment]
you should mention that, anyway what that problem was doing ?

**Comment by tommyettinger** [comment]
No, I shouldn't mention that, because I don't provide builds other than the official one I'm mirroring... The issue was in how my build system was set up for interop between native code and C#, and I don't know how the original repo did this (the requirements to build BLT are basically undocumented, at least for Windows, last time I tried). If someone else knew how to build this code, which I don't, they probably could get .NET working. Anyway, the official binaries in the releases should work just fine, other than the box drawing bug...

That problem was, when box drawing characters are automatically generated by BLT, 2 or 3 of the roughly 120 generated characters are incorrect (meaning in a roguelike or similar game using them, walls appear to go off into nowhere or appear from nowhere, and in a GUI app, boxes sometimes look broken). This only applies to thick-line box drawing characters, I think, so it's relatively easy to miss. I think it also only applies to generated box drawing characters, not ones drawn from a .ttf font that contains that block of chars. However, most .ttf box drawing characters don't line up correctly due to quirks of metrics in most fonts and renderers, so the generated ones are a much better option if they can work.

I've pretty much given up on BLT, and if I was starting a .NET text-based roguelike from scratch today I would probably use [SadConsole](https://sadconsole.com/). BLT is well-designed, but the native-code part makes it a pain to work with from other platforms, like .NET or especially the JVM (which is completely unsupported by this, but it's my main platform of choice). If you're already using C or C++, then BLT remains a strong contender, despite the lack of updates for the last few years. This assumes whoever is using BLT is fully proficient with the build tools it uses. If you do choose BLT, make sure to test basic "Hello, World!" examples on other computers early on, to make sure everything's in order. Good luck!
